
services:
  app:
    build: .
    ports:
      - "4111:4111"
    environment:
      - PORT=4111
      - DATABASE_URL=postgres://user:password@db:5432/perspective
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: perspective
    volumes:
      - ./db:/docker-entrypoint-initdb.d

